AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudWatch alarms for AWS Service Quotas monitoring"

Parameters:
  EC2QuotaThreshold:
    Type: Number
    Description: "Threshold percentage for EC2 quota utilization"
    Default: 80
    MinValue: 1
    MaxValue: 100
  NotificationEmail:
    Type: String
    Description: "Email address to receive quota alerts"

Resources:
  QuotaAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "AWS Service Quotas Alerts"
      TopicName: "service-quotas-alerts"

  QuotaAlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudwatch.amazonaws.com
            Action: sns:Publish
            Resource: !Ref QuotaAlertsTopic
      Topics:
        - !Ref QuotaAlertsTopic

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref QuotaAlertsTopic
      Endpoint: !Ref NotificationEmail

  ELBListenersPerNetworkQuotaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-elb-listeners-quota"
      AlarmDescription: !Sub "Alarm when ELB listeners per network exceeds ${ELBQuotaThreshold}%"
      ActionsEnabled: true
      AlarmActions:
        - !Ref QuotaAlertsTopic
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: !Ref ELBQuotaThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Metrics:
        - Id: usage_data
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/Usage
              MetricName: ResourceCount
              Dimensions:
                - Name: Class
                  Value: None
                - Name: Resource
                  Value: ListenersPerNetworkLoadBalancer
                - Name: Service
                  Value: Elastic Load Balancing
                - Name: Type
                  Value: Resource
            Period: 300
            Stat: Maximum
        - Id: pct_utilization
          Label: "% Utilization"
          ReturnData: true
          Expression: (usage_data/SERVICE_QUOTA(usage_data))*100

  ELBTargetGroupsQuotaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-elb-target-groups-quota"
      AlarmDescription: !Sub "Alarm when ELB target groups per region exceeds ${ELBQuotaThreshold}%"
      ActionsEnabled: true
      AlarmActions:
        - !Ref QuotaAlertsTopic
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: !Ref ELBQuotaThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Metrics:
        - Id: usage_data
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/Usage
              MetricName: ResourceCount
              Dimensions:
                - Name: Class
                  Value: None
                - Name: Resource
                  Value: TargetGroupsPerRegion
                - Name: Service
                  Value: Elastic Load Balancing
                - Name: Type
                  Value: Resource
            Period: 300
            Stat: Maximum
        - Id: pct_utilization
          Label: "% Utilization"
          ReturnData: true
          Expression: (usage_data/SERVICE_QUOTA(usage_data))*100

  AutoScalingGroupsQuotaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-asg-quota"
      AlarmDescription: !Sub "Alarm when Auto Scaling Groups count exceeds ${ASGQuotaThreshold}%"
      ActionsEnabled: true
      AlarmActions:
        - !Ref QuotaAlertsTopic
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: !Ref ASGQuotaThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Metrics:
        - Id: usage_data
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/Usage
              MetricName: ResourceCount
              Dimensions:
                - Name: Class
                  Value: None
                - Name: Resource
                  Value: NumberOfAutoScalingGroup
                - Name: Service
                  Value: AutoScaling
                - Name: Type
                  Value: Resource
            Period: 300
            Stat: Maximum
        - Id: pct_utilization
          Label: "% Utilization"
          ReturnData: true
          Expression: (usage_data/SERVICE_QUOTA(usage_data))*100

  FirehoseStreamsQuotaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-firehose-streams-quota"
      AlarmDescription: !Sub "Alarm when Firehose delivery streams count exceeds ${FirehoseQuotaThreshold}%"
      ActionsEnabled: true
      AlarmActions:
        - !Ref QuotaAlertsTopic
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: !Ref FirehoseQuotaThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Metrics:
        - Id: usage_data
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/Usage
              MetricName: ResourceCount
              Dimensions:
                - Name: Class
                  Value: None
                - Name: Resource
                  Value: DeliveryStreams
                - Name: Service
                  Value: Firehose
                - Name: Type
                  Value: Resource
            Period: 300
            Stat: Maximum
        - Id: pct_utilization
          Label: "% Utilization"
          ReturnData: true
          Expression: (usage_data/SERVICE_QUOTA(usage_data))*100

  EC2vCPUQuotaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-ec2-vcpu-utilization"
      AlarmDescription: !Sub "Alarm when EC2 vCPU utilization exceeds ${EC2QuotaThreshold}%"
      ActionsEnabled: true
      AlarmActions:
        - !Ref QuotaAlertsTopic
      EvaluationPeriods: 2
      DatapointsToAlarm: 2
      Threshold: !Ref EC2QuotaThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Metrics:
        - Id: usage_data
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/Usage
              MetricName: ResourceCount
              Dimensions:
                - Name: Class
                  Value: Standard/OnDemand
                - Name: Resource
                  Value: vCPU
                - Name: Service
                  Value: EC2
                - Name: Type
                  Value: Resource
            Period: 300
            Stat: Maximum
        - Id: pct_utilization
          Label: "% Utilization"
          ReturnData: true
          Expression: "(usage_data/SERVICE_QUOTA(usage_data))*100"

Outputs:
  SNSTopicARN:
    Description: "ARN of the SNS topic"
    Value: !Ref QuotaAlertsTopic
  LogGroupName:
    Description: "Name of the CloudWatch Log Group for alerts"
    Value: !Ref QuotaAlarmsLogGroup
